CREATE TABLE TIME(
    NOME VARCHAR2(50) PRIMARY KEY,
    ESTADO CHAR(2) NOT NULL,
    TIPO VARCHAR2(12) NOT NULL,
    SALDO_GOLS NUMBER(2) NOT NULL,
    CONSTRAINT TIPO_TIME CHECK (UPPER(TIPO) IN ('AMADOR', 'PROFISSIONAL'))
    );

CREATE TABLE JOGA(
    TIME1 VARCHAR2(50) NOT NULL,
    TIME2 VARCHAR2(50) NOT NULL,
    CLASSICO CHAR(1) NOT NULL,
    CONSTRAINT PK_JOGA PRIMARY KEY(TIME1, TIME2),
    CONSTRAINT FK_TIME1 FOREIGN KEY(TIME1) REFERENCES TIME(NOME),
    CONSTRAINT FK_TIME2 FOREIGN KEY(TIME2) REFERENCES TIME(NOME),
    CONSTRAINT CK_TIMES CHECK(UPPER(TIME1)!= UPPER(TIME2)),
    CONSTRAINT CK_CLASSICO CHECK(UPPER(CLASSICO) IN('S','N'))
    );
    
CREATE TABLE PARTIDA(
    TIME1 VARCHAR2(50) NOT NULL,
    TIME2 VARCHAR2(50) NOT NULL,
    DATA DATE NOT NULL,
    PLACAR VARCHAR(5) DEFAULT '0X0',
    LOCAL VARCHAR(20),
    CONSTRAINT PK_PARTIDA PRIMARY KEY(TIME1, TIME2, DATA),
    CONSTRAINT FK_TIMES FOREIGN KEY(TIME1, TIME2) REFERENCES JOGA(TIME1, TIME2),
    CONSTRAINT CK_PLACAR CHECK(REGEXP_LIKE(PLACAR,'[[:digit:]]{1,2}\X[[:digit:]]{1,2}', 'i' ))
    );
    
CREATE TABLE JOGADOR(
    CPF CHAR(14) NOT NULL PRIMARY KEY,
    RG VARCHAR(20) NOT NULL,
    NOME VARCHAR2(20),
    DATA_NASC DATE NOT NULL,
    NATURALIDADE VARCHAR2(20),
    TIME VARCHAR(50),
    CONSTRAINT FK_JOGADOR FOREIGN KEY(TIME) REFERENCES TIME(NOME),
    CONSTRAINT CK_CPF CHECK(REGEXP_LIKE(CPF, '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}'))
    );
    
CREATE TABLE POSICAO(
    JOGADOR CHAR(14) NOT NULL,
    POSICAO VARCHAR(10) NOT NULL,
    CONSTRAINT PK_POSICAO PRIMARY KEY(JOGADOR, POSICAO),
    CONSTRAINT FK_POSICAO FOREIGN KEY(JOGADOR) REFERENCES JOGADOR(CPF) ON DELETE CASCADE,
    CONSTRAINT CK_POSICAO CHECK(UPPER(POSICAO) IN ('GOLEIRO', 'LATERAL', 'ZAGUEIRO', 'VOLANTE', 'MEIO CAMPO', 'ATACANTE', 'PONTA', 'MEIA'))
    );
    
CREATE TABLE DIRETOR(
    TIME VARCHAR2(50) NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    CONSTRAINT PK_DIRETOR PRIMARY KEY(TIME, NOME),
    CONSTRAINT FK_DIRETOR FOREIGN KEY(TIME) REFERENCES TIME(NOME) ON DELETE CASCADE
    );
    
CREATE TABLE UNIFORME(
    TIME VARCHAR2(50) NOT NULL,
    TIPO CHAR(7) NOT NULL,
    COR_PRINCIPAL VARCHAR2(10),
    CONSTRAINT PK_UNIFORME PRIMARY KEY(TIME, TIPO),
    CONSTRAINT FK_UNIFORME FOREIGN KEY(TIME) REFERENCES TIME(NOME) ON DELETE CASCADE,
    CONSTRAINT CK_UNIFORME CHECK(UPPER(TIPO) IN('TITULAR', 'RESERVA'))
    );
    
    
    select 'drop table '||table_name||' cascade constraints;' from user_tables;
    
    